const profile = [
  {
    name1: "Prasad G Kadam",
    role1: "Chair",
    image1: "prasad",
    instaId1: "https://www.instagram.com/mnmslimshady8/",
    name2: "Shreya Gadatarannavar",
    role2: "Vice-Chair",
    image2: "shreya",
    instaId2: "https://www.instagram.com/shreya_gaddu",
    id: 1,
  },

  {
    name1: "Vijaylakshmi Lokhande",
    role1: "Secretary",
    image1: "vijayal",
    instaId1: "https://www.instagram.com/vl_vijayalakshmi/",
    name2: "Shreejit Savadatte",
    role2: "Treasure",
    image2: "shreejit",
    instaId2: "https://www.instagram.com/shreejit_18/",
    id: 2,
  },
  {
    name1: "Somangouda Patil",
    role1: "SBMDC Chair",
    image1: "soma",
    instaId1: "https://www.instagram.com/patilsomu_/",
    name2: "Parwathreddy Madani",
    role2: "Event lead",
    image2: "parwath",
    instaId2: "https://www.instagram.com/parwathmadni/",
    id: 3,
  },
  {
    name1: "Amogh Mathad",
    role1: "Student Activity Co-ordinator",
    image1: "profile",
    instaId1: "https://www.instagram.com/amoghmathad/",
    name2: "Sourabh Kulkarni",
    role2: "Co- Student Activity Coordinator",
    image2: "profile",
    instaId2: "https://www.instagram.com/",
    id: 4,
  },
  {
    name1: "Parshuram Gore",
    role1: "Publicity Lead",
    image1: "parshu",
    instaId1: "https://www.instagram.com/lazywiz007/",
    name2: "Priyadarshini Desai",
    role2: "WIE Chair",
    image2: "priya",
    instaId2: "https://www.instagram.com/priyaaa.desai/",
    id: 5,
  },
  {
    name1: "Disha Shedshyal",
    role1: "WIE Vicechair",
    image1: "disha",
    instaId1: "https://www.instagram.com/disha_shedshyal/",
    name2: "",
    role2: "",
    image2: "profile",
    instaId2: "/",
    id: 6,
  },
];

export default profile;
