const techCards = [
  {
    title: "How Robots are Improving our Health",
    image: "cardImageBackground1",
    description:"Robots are everywhere from science fiction... ",
    link:"https://transmitter.ieee.org/robotics/",
    id: 1,
  },
  {
    title: "Follow the timeline to see how Generation AI will be impacted by technology",
    image: "cardImageBackground2",
    description: "The next generation of children will be literally embedded into Artificial Intelligence(AI).From robotic toys and social media networks, to the classroom and home, artificial intelligence (AI) is ubiquitous in the daily life of a child.  ",
    link:"https://transmitter.ieee.org/ai-2017/",
    id: 2,
  },
  {
    title: "Space Exploration,Technology and our lives ",
    image: "cardImageBackground3",
    description: "Space technology has helped astronauts and scientists to research stars, planets, and the creation of the universe. ",
    link:"https://transmitter.ieee.org/natural-capital-2019/",
    id: 3,
  },
  {
    title: "Learn how your IoT data can be used by experiencing a day in a connected life",
    image: "cardImageBackground4",
    description: "IoT and Big Data are buzzing the technology world for quite a time now, and these are no longer a “nice to have” technology but a necessity. ",
    link:"http://transmitter.ieee.org/iot-2017/",
    id: 4,
  },
  {
    title: "How Technology, Privacy and Security are Changing Each Other (And Us)",
    image: "cardImageBackground5",
    description: "Wireless networks allow employees to work from anywhere, often using their personal devices. Many employees can now work from anywhere with a steady signal, such as coffee shops, airports and airplanes. ",
    link:"https://transmitter.ieee.org/privacy-and-security-2019/",
    id: 5,
  },
  {
    title: "Enter our virtual home to explore the IoT technologies",
    image: "cardImageBackground6",
    description:"A smart home refers to a convenient home setup where appliances and devices can be automatically controlled remotely from anywhere with an internet connection using a mobile or other networked device.  ",
    link:"https://transmitter.ieee.org/iot-2016/",
    id: 6,
  },
  {
    title: "Harnessing and Sustaining our Natural Resources",
    image: "cardImageBackground7",
    description: "Technology plays an important role in enabling us to utilize nature’s gifts in ways that positively impact our lives. ",
    link:"https://transmitter.ieee.org/category/impact-theme/sustainable-natural-capital/",
    id: 7,
  },
  {
    title: "Exceptional Infrastructure Challenges, Technology and Humanity",
    image: "cardImageBackground8",
    description:"As the world experiences unprecedented challenges, our ability to tap technology — to swiftly adapt and secure communications, work remotely, and reconfigure manufacturing platforms to address critical needs — has never been more important. ",
    link:"https://transmitter.ieee.org/category/impact-theme/infrastructure/",
    id: 8,
  },
  {
    title: "Watch technical experts discuss the latest cyber threats",
    image: "cardImageBackground9",
    description: "A host of new and evolving cybersecurity threats has the information security industry on high alert. ",
    link:"https://transmitter.ieee.org/category/cybersecurity/",
    id: 9,
  },
  {
    title: "Explore an interactive map showcasing exciting innovations in robotics ",
    image: "cardImageBackground10",
    description:"Places of Invention is an ongoing, multifaceted research project at the Lemelson Center. ",
    link:"https://transmitter.ieee.org/robotics-2016/ ",
    id: 10,
  },
  {
    title: "THE Global Impact OF IEEE'S",
    image: "cardImageBackground11",
    description: "IEEE’s family of 802 networking standards paved the way for global innovation and connectivity. We invite you to explore how 802 enabled our hyper-connected world and the future of connectivity.",
    link:"https://transmitter.ieee.org/802-standards/",
    id: 11,
  },
  {
    title: "Global Innovation and the Environment",
    image: "cardImageBackground12",
    description:"Our planet is ready to address environmental challenges through technological transformation. ",
    link:"https://transmitter.ieee.org/environment/",
    id: 12,
  },
  {
    title: "IEEE Experts and the Robots They are Teaching",
    image: "cardImageBackground13",
    description: "One of today’s most advanced wheelchairs is being pioneered by Ming Liu, IEEE Senior Member and Assistant Professor at Hong Kong University of Science and Technology.",
    link:"https://transmitter.ieee.org/interactive-experiences/robotics-2017/",
    id: 13,
  },
  {
    title: "Interactively explore A.I. in recent Hollywood movies",
    image: "cardImageBackground14",
    description:"The entertainment and media (E&M) industry is a diverse sector composed of multiple segments including film, television and media streamed online. ",
    link:"http://transmitter.ieee.org/ai-2016/",
    id: 14,
  },
  {
    title: "Listen to technical experts discuss the biggest security threats today",
    image: "cardImageBackground15",
    description: "Each year brings new technological developments that improve people’s lives.  Unfortunately, these advances also mean new cybersecurity threats and more attack surfaces.  Indeed, as this IEEE survey infographic illustrates, Chief Information Officers and Chief Technology Officers say that their biggest challenge in 2017 will be online security threats. ",
    link:"https://transmitter.ieee.org/ieee-cyber-security/",
    id: 15,
  },
];

export default techCards;